### ISSUE TITLE
Sapper throws error 500

### ISSUE THREAD

**Issue by Hejtmus** [andrelmlins/svelte-infinite-scroll#12]
Hello developers,

I love this component, but when I use it in Sapper, it throws error 500.
I tried binding scroll of some element or window, unfortunately it threw "Cannot read property 'parentNode' of undefined".
I guess this is caused by Sapper which runs before DOM is rendered, so nothing like window or parentNode exists. Maybe getting those elements in onMount( () => {...} ) would help. I think you tried that (me too, but I still get some errors), because I saw unused onMount import. But if you haven't, at least I reminded you. BTW, scrolling feature doesn't work for me on mobile devices, but that is for another issue.

Best regards,
Filip Holčík.

**Comment by andrelmlins** [comment]
Thank you for reporting this issue, I'm already analyzing.

**Comment by andrelmlins** [comment]
Hi @Hejtmus , this is a recurring problem in other projects. I made a change to read the element in onMount, I believe this change solves the problem.

Soon a new version.

**Comment by andrelmlins** [comment]
Version 1.5.0
