### ISSUE TITLE
Can no longer bind to window, only binds to components parent.

### ISSUE THREAD

**Issue by csell5** [andrelmlins/svelte-infinite-scroll#13]
@andrelmlins first thank you for the great work on this package. We've enjoyed using it.

It looks like window scroll binding isn't working as it used to. You have a function called getElement that used to get called to set your element that you bind your scrolling too but that function isn't getting called any longer and the element always becomes the component's parent even if you set `window = true`

https://github.com/andrelmlins/svelte-infinite-scroll/blob/master/src/lib/InfiniteScroll.svelte#L26

**Comment by andrelmlins** [comment]
@csell5  thank you very much for reporting this. This is really a problem, I'm already correcting.

**Comment by andrelmlins** [comment]
Corrected in https://github.com/andrelmlins/svelte-infinite-scroll/commit/e19c42b54f726ae0855d1c9224a3b3822e31f4fe

**Comment by andrelmlins** [comment]
@csell5 could you validate in version 1.5.1?

**Comment by csell5** [comment]
for sure.. I'll do it here in a few.

**Comment by csell5** [comment]
@andrelmlins and confirmed. We've upgraded and pushed to production. Thanks again for the quick fix!
