### ISSUE TITLE
any idea how it can work on Sapper 

### ISSUE THREAD

**Issue by leonkalema** [andrelmlins/svelte-infinite-scroll#2]
amazing plugin that at the moment breaks on sapper because of SSR

**Comment by andrelmlins** [comment]
Hello @leonkalema, I am analyzing the problem

**Comment by andrelmlins** [comment]
Support for sapper was added in version 1.0.0

Commit -> https://github.com/andrelmlins/svelte-infinite-scroll/commit/1c7d5bc133fbc460be637c932f193f485c885822

Let me know if it's working.

**Comment by andrelmlins** [comment]
There is a related question https://github.com/sveltejs/sapper/issues/774

Installing svelte-infinite-scroll as a devDependency allows Svelte to compile the svelte-infinite-scroll components right along with the rest of your code.

Or import the library that way:

```
import SvelteInfiniteScroll from "svelte-infinite-scroll/dist/index.svelte";
```
