### ISSUE TITLE
Optional Types

### ISSUE THREAD

**Issue by Zellerich** [andrelmlins/svelte-infinite-scroll#27]
`Type '{ threshold: number; hasMore: boolean; elementScroll: any; }' is not assignable to type 'IntrinsicAttributes & InfiniteScrollProps'.
  Type '{ threshold: number; hasMore: boolean; elementScroll: any; }' is missing the following properties from type 'InfiniteScrollProps': horizontal, reverse, window`

I get this TypeScript Error. But I guess some properties are optional. Can you maybe change those to be optional in the Types?

**Comment by andrelmlins** [comment]
Thanks for reporting this issue. I made a new version(2.0.1) available to fix this.
