### ISSUE TITLE
Add pagination example 

### ISSUE THREAD

**Issue by kilianso** [andrelmlins/svelte-infinite-scroll#6]
Hey there! Nice work!

Could you please add a pagination example where the data is fetched and appended in batches/pages rather than have the whole dataset loaded initially? That would be super helpful. Thanks a lot!

**Comment by andrelmlins** [comment]
Hello @kilianso, communicating with an API? Do you have any suggestions?

**Comment by kilianso** [comment]
> communicating with an API? 
Yes, exactly. One way to do it is fetching the first batch of data `onMount` and then, whenever the `loadMore`event triggers, pushing the next batch to the `data` array.

I made a quick REPL:
https://svelte.dev/repl/4863a658f3584b81bbe3d9f54eb67899?version=3.20.1

> Do you have any suggestions?
1. Maybe you could add something like a mode to choose from. Like `batches: single | multiple`
2. Not sure if the `threshold` will work properly when using an API that responds with delay or when you have a slow internet connection. Maybe adding a loader?
3. I think it would be a performance enhancement if you work with `requestAnimationFrame` rather than listening to scroll events. Or you could observe the top position of your InfiniteScroll component related to the viewport using `IntersectionObserver` and trigger an event once it is intersecting. That way, you don't have to calculate the offset all the time during scrolling.

Great project! Hope you keep going :)

**Comment by andrelmlins** [comment]
Excellent @kilianso, could you create a PR by inserting a second card on the example page, with your example?

I will work on the other 2 points. I hope to count on your help. Thank you very much.

**Comment by andrelmlins** [comment]
Example inserted in the README
