### ISSUE TITLE
Importing as a Svelte component

### ISSUE THREAD

**Issue by antony** [andrelmlins/svelte-infinite-scroll#7]
I noticed that there are some inconsistencies in your docs / project structure.

From `package.json` you have the key `svelte`:`dist/index.svelte`, but the `svelte` key is designed for Svelte apps to import Svelte components, so it shouldn't be looking in dist.

In the readme you suggest importing from `svelte-infinite-scroll/index.svelte` which doesn't exist.

So in summary I think you should be setting the `svelte` key in `package.json` to point to `src/lib/index.svelte` which should be called `src/lib/InfiniteScroll.svelte` (components should have capitalised names), and you should be recommending people use it in Svelte/Sapper apps as:

`import InfiniteScroll from 'svelte-infinite-scroll'`

Also, all Svelte / Sapper apps are bundled so components should *always* be installed as a dev dependency unless your consuming component is also a component library.

I look forward to using it!

**Comment by andrelmlins** [comment]
Hello antony, happy to have you here, is the svelte key needed in a library?

**Comment by andrelmlins** [comment]
Implemented in the https://github.com/andrelmlins/svelte-infinite-scroll/commit/830fe53973b756ad5c24bbf89296137fa6f385d8 commit, let me know if this has been resolved?

**Comment by antony** [comment]
Thanks, I'll take a look asap.
