### ISSUE TITLE
Invert scrolling direction

### ISSUE THREAD

**Issue by cupcakearmy** [andrelmlins/svelte-infinite-scroll#8]
Thanks for the work you have done so far!

Is there a way to invert the behaviour? Say a chat, where the next messages would be loaded from the top and not the bottom. Is that possible?

**Comment by andrelmlins** [comment]
Hello @cupcakearmy,

You can do this by changing the style. Note the comments for the modified lines in this example:

https://svelte.dev/repl/36d00aa55c7c4ff68914ce314f4e1ca4

**Comment by cupcakearmy** [comment]
You genius! Smart move. 
On mobile that works perfectly, on desktop it inverts the scrolling direction for the user input device, which is quite confusing. also the scroll bar is on the left rather then on the right.

**Comment by andrelmlins** [comment]
I didn't see this error, I will have to make an implementation in the library. I modified the example with the change I will need to make. Let me know if it works well.

https://svelte.dev/repl/36d00aa55c7c4ff68914ce314f4e1ca4

**Comment by cupcakearmy** [comment]
perfect! works like a charm ❤️

**Comment by cupcakearmy** [comment]
Thanks for the super fast replies ;)

**Comment by andrelmlins** [comment]
Inserted in version 1.3.0
