### ISSUE TITLE
onDestroy doesn't remove event listeners

### ISSUE THREAD

**Issue by algusarov** [andrelmlins/svelte-infinite-scroll#9]
I use the component on window and needed to rewrite onDestroy method of InfiniteScroll from:
```
onDestroy(() => {
    if (component || elementScroll || window) {
      const element = getElement();
      element.removeEventListener("scroll", null);
      element.removeEventListener("resize", null);
    }
  });
```
to:
```
onDestroy(() => {
    if (component || elementScroll || window) {
      const element = getElement();
      element.removeEventListener("scroll", onScroll);
      element.removeEventListener("resize", onScroll);
    }
  });
```
... to make it properly remove the event handler (otherwise I was getting multiple event handlers on window after going back and forth between components. I think that this version is also in line with what MDN says about how to use removeEventListener: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

**Comment by andrelmlins** [comment]
Hello @algusarov , are you interested in sending a pull request to correct this?

**Comment by algusarov** [comment]
Yes, can do! Will need a non-master branch to commit to? While we are at it, I would also propose to remove if condition in onDestroy() all together as component always exist at this point due to binding to it here:
`<div bind:this={component} style="width:0px" />`

**Comment by andrelmlins** [comment]
Create the fork, make changes and create the pull request. I think it's worth doing all at the same time.

```js
const element = getElement();
      element.removeEventListener("scroll", onScroll);
```

**Comment by algusarov** [comment]
Ok done now. Thanks for making this component by the way, it was very usefull for my small project.
